### PR TITLE
Fix bugs and make the widget independent on scroll controller.

### PR DESCRIPTION
**Pull request by darkstarx**
Hi!
It fixes the bug with initState and makes the widget working properly without specifying the ScrollController and scrollDirection. Now it can determine scroll metrics (including scroll axis) using Notifiers. There is no need also to access the PrimaryScrollController since it may not exist on the current context.

### CODE REVIEW

**Comment by memoriasIT** [comment]
I am not 100% sure if what you explain is exactly my error, but I encountered this:

```
I/flutter ( 1494): The following exception was thrown building Expanded(flex: 1)
I/flutter ( 1494): :
I/flutter ( 1494): dependOnInheritedWidgetOfExactType<PrimaryScrollController>() or dependOnInheritedElement() was called before _ScrollShadowState.initState() completed.
I/flutter ( 1494): When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
I/flutter ( 1494): Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
I/flutter ( 1494): debugCreator: Expanded ← Column ← _ListViewOverlay ← Builder ← Semantics ← _FocusInheritedScope ← Focus ← _InheritedProviderScope<SearchCubit?> ← InheritedProvider<SearchCubit> ← BlocProvider<SearchCubit> ← MapOverlay ← Positioned ← ⋯
I/flutter ( 1494): #0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5321:9)
I/flutter ( 1494): #1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:5364:6)
I/flutter ( 1494): #2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4383:14)
I/flutter ( 1494): #3      PrimaryScrollController.maybeOf (package:flutter/src/widgets/primary_scroll_controller.dart:142:53)
I/flutter ( 1494): #4      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:160:42)
I/flutter ( 1494): #5      _ScrollShadowState.initState (package:flutter_scroll_shadow/src/scroll_shadow.dart:119:55)
I/flutter ( 1494): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5219:55)
I/flutter ( 1494): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
I/flutter ( 1494): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
I/flutter ( 1494): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3702:20)
I/flutter ( 1494): #10     ComponentElement.performRebuild (package:f
```

I got this error with a similar setup to:
```
Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Expanded(
          child: ScrollShadow(
            color: context.materialTheme.backgroundColor,
            child: Text('test'),
          ),
        ),
      ],
    )
```

This does not happen with version 1.0.2
Flutter doctor:
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)

Edit: I now saw that you commented the same issue I am having in issue #8, so perhaps it's different issues.

**Comment by darkstarx** [comment]
@memoriasIT does this happen on my PR revision? Could you provide me with full example of code to reproduce the error, please?
As far as I can see, the mistake is in the `_ScrollShadowState.initState (package:flutter_scroll_shadow/src/scroll_shadow.dart:119:55)`. There is no `initState` now in my version of code, so it seems that you tried to create `ScrollShadow` without ScrollController on the current version of package, which contains the bug.

**Comment by memoriasIT** [comment]
Okay nice, I checked on your revision and it doesn't seem to happen indeed :)
For me this would trigger the error with the package from pub dev:
```
import 'package:flutter/material.dart';
import 'package:flutter_scroll_shadow/flutter_scroll_shadow.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Expanded(
            child: ScrollShadow(
              color: Colors.red,
              child: CustomScrollView(
                physics: const ClampingScrollPhysics(),
                slivers: [],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by darkstarx** [comment]
> For me this would trigger the error with the package from pub dev

Yeah, for me too ) That's why I suggested the maintainer to merge this PR.

**Review by rickypid — CHANGES_REQUESTED** [review]
Hi @darkstarx,

Thanks for your PR, I see you've cleaned up the handling with controller declaration. Very good!

I kindly ask you if you can update the CHANGELOG.md with your contribution and then I will merge the changes.

**Comment by darkstarx** [comment]
Hi @rickypid, sure, no problem. Did it and updated the commit.

**Pull request merged**
