### PR TITLE
Consume scroll notification

### PR DESCRIPTION
**Pull request by pixelshot91**
Enable to nest mulitple ScrollShadow without the inner one interfering with the outer one

### CODE REVIEW

**Comment by RichiB20** [comment]
Hi @pixelshot91, I tried to reproduce your scenario of a ScrollShadow inside another ScrollShadow. However the behavior with and without your change for me is the same. Could you tell me which differences you found? 
Thank you

**Comment by pixelshot91** [comment]
I made two video showcasing the bug fix.
[before_fix.webm](https://github.com/rickypid/flutter_scroll_shadow/assets/19229808/74026c29-a997-4347-ad73-32aebb6f0dd9)
In this video, scrolling up and down works as expected, but when I scroll in the inner ScrollShadow, I have two huge shadows left and right, but there should not be. There should just be the little shadow left and right for each row.

[after_fix.webm](https://github.com/rickypid/flutter_scroll_shadow/assets/19229808/2de715a6-3060-472a-9e4a-0e720f755277)
In this video, evrything works as expected

The code used to create the video is available here:
https://github.com/pixelshot91/flutter_scroll_shadow/tree/topic/consume_notification_test
The test is not mergeable yet. I need to add some 'expect' to check the position of the big shadow

**Comment by RichiB20** [comment]
Sorry, I tried the two scroll shadow in the same  direction and I did't see any problem. 
You're right, when you finish the test I will accept your PR.
Thank you for your work

**Comment by pixelshot91** [comment]
I added the test and a 'flutter test' step in the workflow

**Comment by pixelshot91** [comment]
Is ok for you ? @RichiB20

**Comment by RichiB20** [comment]
Yes it's ok, as soon as @rickypid is able he will accept the PR.

**Comment by rickypid** [comment]
Hi @pixelshot91,

Sorry for the delay but it's a very intense period,

Thanks to you and @RichiB20 for the contribution.

**Pull request merged**
